In [5]:
# 1. Import of packages

import pandas as pd
import geopandas as gpd
from shapely import wkt

In [6]:
# 2. Read population data excel and arrange 2013 - 2025 total population for 'Quartiere' to one csv worksheet

fp = "../data/raw/BEV321T3211_auslaendische-Wohnbevoelkerung_Bevoelkerung_nach-Herkunft-Stadtkreis-Stadtquartier.xlsx"

# Years to include
years = range(2013, 2026)

# Empty list to store yearly data
all_years = []

for year in years:

    # Read one sheet (= one year)
    year_df = pd.read_excel(
        fp,
        sheet_name=str(year),
        skiprows=8
    )

    # Rename first column
    year_df = year_df.rename(columns={"Unnamed: 0": "quartier"})

    # Keep only relevant columns
    year_df = year_df[["quartier", "Total"]]

    # Remove "Ganze Stadt"
    year_df = year_df[year_df["quartier"] != "Ganze Stadt"]

    # Remove "Kreis" rows ("~" reverses True/False)
    year_df = year_df[~year_df["quartier"].str.startswith("Kreis")]

    # Rename "Total" column to the corresponding year
    year_df = year_df.rename(columns={"Total": str(year)})

    # Store cleaned dataframe
    all_years.append(year_df)

# Merge all years together
pop_df = all_years[0]

for df in all_years[1:]:
    pop_df = pop_df.merge(df, on="quartier")

# Save as CSV
output_file = "../data/cleaned/quartier_population_2013_2025.csv"

pop_df.to_csv(output_file, index=False)

print("CSV successfully created!")

display(pop_df.head())

print("Data loaded successfully")

display(pop_df.head())
pop_df.info()

CSV successfully created!

,quartier,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Rathaus,3194,3236,3197,3226,3266,3267,3307,3317,3275,3330,3343,3260,3252
1,Hochschulen,665,634,641,640,677,664,678,675,701,676,695,684,688
2,Lindenhof,923,955,974,972,955,990,1009,1010,1024,1034,1046,1040,1038
3,City,783,791,805,810,830,829,797,829,817,820,806,785,769
4,Wollishofen,15937,16137,16244,16567,17892,18923,19225,19757,19937,20570,21181,21800,22029

Data loaded successfully

,quartier,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Rathaus,3194,3236,3197,3226,3266,3267,3307,3317,3275,3330,3343,3260,3252
1,Hochschulen,665,634,641,640,677,664,678,675,701,676,695,684,688
2,Lindenhof,923,955,974,972,955,990,1009,1010,1024,1034,1046,1040,1038
3,City,783,791,805,810,830,829,797,829,817,820,806,785,769
4,Wollishofen,15937,16137,16244,16567,17892,18923,19225,19757,19937,20570,21181,21800,22029

<class 'pandas.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   quartier  34 non-null     str
 1   2013      34 non-null     int64
 2   2014      34 non-null     int64
 3   2015      34 non-null     int64
 4   2016      34 non-null     int64
 5   2017      34 non-null     int64
 6   2018      34 non-null     int64
 7   2019      34 non-null     int64
 8   2020      34 non-null     int64
 9   2021      34 non-null     int64
 10  2022      34 non-null     int64
 11  2023      34 non-null     int64
 12  2024      34 non-null     int64
 13  2025      34 non-null     int64
dtypes: int64(13), str(1)
memory usage: 4.1 KB

In [ ]:
# cleaning and preparing the data of population per neighbourhood with Pandas

In [4]:
import os
print(os.getcwd())

C:\Users\lukas\OneDrive\Desktop\Privat\UZH\FS 26\Spatial Programming\sds210_project\notebooks