In [1]:
import pandas as pd
import geopandas as gpd

In [2]:
# 1. Loading the cleaned data of Zueriwieneu requests, neighbourhoods and population

reports_gdf = gpd.read_file("../data/cleaned/stzh.zwn_meldungen_p_cleaned.gpkg")
pop_quartiere_gdf = gpd.read_file("../data/cleaned/pop_quartiere_2013_2025.gpkg")

# 2. Assign reports to their nearest neighbourhoods (a few lie just directly outside the city boarder, thus "nearest" was used instead of "within" or "intersects")

reports_quartier = gpd.sjoin_nearest(
    reports_gdf,
    pop_quartiere_gdf,
    how="left"
)

print(f"{reports_quartier['qname'].isna().sum()} reports were not assigned to a neighbourhood")

0 reports were not assigned to a neighbourhood

In [3]:
# (1) How does number of reports evolve over the years, diurnal and across neighbourhoods?

# Extract year
reports_gdf["year"] = (
    reports_gdf["requested_datetime"].dt.year
)

# (1.1) Count the total number of reports per year
report_counts_year = (
    reports_gdf
    .groupby("year")
    .size()
    .reset_index(name="report_count")
)

print("Note: Only 2014-2025 are whole years with reports\n")
display(report_counts_year)

# Extract hour of day
reports_gdf["hour"] = reports_gdf["requested_datetime"].dt.hour

# (1.2) Count the total number of reports per hour
report_counts_hour = (
    reports_gdf
    .groupby("hour")
    .size()
    .reset_index(name="report_count")
)

display(report_counts_hour)

# (1.3) Count total reports per neighbourhood normalized by mean population from 2013-2025

# Asses mean population over the reporting period
population_cols = [
    "2013", "2014", "2015", "2016", "2017",
    "2018", "2019", "2020", "2021", "2022",
    "2023", "2024", "2025"
]

pop_quartiere_gdf["mean_pop_2013-2025"] = (
    pop_quartiere_gdf[population_cols]
    .mean(axis=1)
)
report_counts_quartier = (
    reports_quartier
    .groupby("qname")
    .size()
    .reset_index(name="report_count")
)

# Join counts back to neighbourhood polygons/population
quartier_analysis = pop_quartiere_gdf.merge(
    report_counts_quartier,
    on="qname",
    how="left"
)

# Calculate reports per 1000 inhabitants
quartier_analysis["reports_per_1000"] = (
    quartier_analysis["report_count"]
    / quartier_analysis["mean_pop_2013-2025"]
) * 1000

display(
    quartier_analysis[
        ["qname", "report_count", "mean_pop_2013-2025", "reports_per_1000"]
    ]
    .sort_values("reports_per_1000", ascending=False)
)

Note: Only 2014-2025 are whole years with reports

    year  report_count
0   2013          2901
1   2014          2139
2   2015          1943
3   2016          2307
4   2017          2869
5   2018          3724
6   2019          5244
7   2020          4804
8   2021          5783
9   2022          6828
10  2023          8325
11  2024         10795
12  2025         11590
13  2026          3159

    hour  report_count
0      0           860
1      1           383
2      2           201
3      3           165
4      4           108
5      5           271
6      6          1085
7      7          2705
8      8          4318
9      9          5026
10    10          4961
11    11          4788
12    12          4697
13    13          4899
14    14          5097
15    15          5160
16    16          5181
17    17          5103
18    18          4206
19    19          3283
20    20          2979
21    21          2993
22    22          2347
23    23          1595

                   qname  report_count  mean_pop_2013-2025  reports_per_1000
15                  City          1739          805.461538       2159.010601
30           Hochschulen          1415          670.615385       2110.002294
24             Lindenhof          1124          997.692308       1126.599846
2            Langstrasse          6175        11509.538462        536.511522
13               Rathaus          1454         3266.923077        445.067106
27                  Werd          1522         4503.307692        337.973797
4                   Enge          2739         9606.384615        285.122875
3            Escher Wyss          1558         5813.076923        268.016409
17              Sihlfeld          5216        21547.692308        242.067685
6                Seefeld          1279         5406.846154        236.551950
26         Gewerbeschule          2225         9579.076923        232.277078
29                  Hard          2842        13028.230769        218.141669
21             Wipkingen          3293        16379.769231        201.040683
25            Hirslanden          1373         7470.230769        183.796196
14             Hottingen          1945        11251.384615        172.867613
23           Unterstrass          3589        23709.769231        151.372203
5                Weinegg           808         5357.692308        150.811199
8            Wollishofen          2827        18938.384615        149.273555
12              Fluntern          1251         8454.846154        147.962479
9              Mühlebach           905         6286.692308        143.954874
0           Alt-Wiedikon          2495        17735.230769        140.680436
10            Oberstrass          1514        10816.615385        139.969847
20                 Höngg          3084        23811.230769        129.518715
19              Oerlikon          2976        23131.769231        128.654232
31           Friesenberg          1408        10948.076923        128.607061
28            Altstetten          4077        33887.000000        120.311624
11  Schwamendingen-Mitte          1228        11204.384615        109.599951
1                Witikon          1130        11069.846154        102.079106
7               Leimbach           629         6209.153846        101.302048
32               Seebach          2617        26209.923077         99.847680
16           Albisrieden          2037        21920.846154         92.925245
18             Affoltern          2407        26490.384615         90.863158
33               Saatlen           676         8491.461538         79.609381
22            Hirzenbach           854        12549.769231         68.049060

In [4]:
# (2) Which neighbourhoods make the most detailed reports (average number of words)?

# Count words in each report detail
reports_quartier["word_count"] = (
    reports_quartier["detail"]
    .str.split() # splits detail in a list of single words
    .str.len() # counts length of the list
)

# Average words per neighbourhood
detail_by_quartier = (
    reports_quartier
    .groupby("qname")["word_count"]
    .mean()
    .reset_index(name="avg_word_count")
    .sort_values("avg_word_count", ascending=False)
)

display(detail_by_quartier)

                   qname  avg_word_count
31             Wipkingen       27.295172
24  Schwamendingen-Mitte       23.226384
9          Gewerbeschule       22.011236
6            Escher Wyss       21.329268
32               Witikon       20.708850
15                 Höngg       20.626135
21              Oerlikon       19.409274
5                   Enge       19.186564
1            Albisrieden       18.923908
28           Unterstrass       18.665366
23               Saatlen       18.631657
13           Hochschulen       17.599293
3             Altstetten       17.312975
8            Friesenberg       17.198864
25               Seebach       17.132595
11            Hirslanden       17.073562
33           Wollishofen       16.611956
12            Hirzenbach       16.478923
4                   City       16.242668
17              Leimbach       16.019078
7               Fluntern       15.717026
19             Mühlebach       15.491713
2           Alt-Wiedikon       15.486573
0              Affoltern       15.185293
26               Seefeld       15.159500
22               Rathaus       15.091472
20            Oberstrass       14.823646
14             Hottingen       14.411311
18             Lindenhof       14.303381
29               Weinegg       14.238861
27              Sihlfeld       13.085123
30                  Werd       11.708279
10                  Hard       11.497185
16           Langstrasse       10.802429

In [5]:
# (3) How long does the processing of the reports by the council take? Did it change over time and neighbourhoods? (only for reports with "status"="fixed - council")

# Define only the reports that were fixed by the municipal offices
fixed_reports = reports_quartier[
    reports_quartier["status"] == "fixed - council"
].copy()

# Calculate processing duration for these reports
fixed_reports["processing_time"] = (
    fixed_reports["updated_datetime"]
    - fixed_reports["requested_datetime"]
)

# recalcualte processing duration to decimal days
fixed_reports["processing_days"] = (
    fixed_reports["processing_time"]
    .dt.total_seconds() / (60 * 60 * 24)
)

# Extract year
fixed_reports["year"] = (
    fixed_reports["requested_datetime"].dt.year
)

# (3.1) Count the average processing duration per year
processing_time_year = (
    fixed_reports
    .groupby("year")["processing_days"]
    .mean()
    .reset_index(name="avg_processing_days")
    .sort_values("year", ascending=True)
)

display(processing_time_year)

# (3.2) Count the average processing duration per neighbourhood
processing_time_by_quartier = (
    fixed_reports
    .groupby("qname")["processing_days"]
    .mean()
    .reset_index(name="avg_processing_days")
    .sort_values("avg_processing_days", ascending=True)
)

display(processing_time_by_quartier)

    year  avg_processing_days
0   2013             3.061863
1   2014             2.444667
2   2015             3.049618
3   2016             3.000544
4   2017             2.540313
5   2018             2.707137
6   2019             1.832676
7   2020             2.906078
8   2021             3.155192
9   2022             3.265625
10  2023             3.607335
11  2024             2.647599
12  2025             5.039091
13  2026             1.992847

                   qname  avg_processing_days
30                  Werd             1.923301
12            Hirzenbach             2.032798
16           Langstrasse             2.122421
27              Sihlfeld             2.153757
10                  Hard             2.205390
26               Seefeld             2.769765
11            Hirslanden             2.782081
19             Mühlebach             2.829791
0              Affoltern             2.890134
15                 Höngg             3.001785
33           Wollishofen             3.098717
9          Gewerbeschule             3.108747
29               Weinegg             3.113380
2           Alt-Wiedikon             3.135239
7               Fluntern             3.175077
28           Unterstrass             3.324423
1            Albisrieden             3.355387
14             Hottingen             3.395875
3             Altstetten             3.445636
24  Schwamendingen-Mitte             3.468702
21              Oerlikon             3.470106
4                   City             3.502328
5                   Enge             3.619071
31             Wipkingen             3.716836
22               Rathaus             3.759842
25               Seebach             3.769060
32               Witikon             3.920960
8            Friesenberg             3.936191
18             Lindenhof             4.333317
20            Oberstrass             4.401343
17              Leimbach             4.976243
13           Hochschulen             4.992131
6            Escher Wyss             5.004916
23               Saatlen             5.087597

In [7]:
# (4) What percentage of reports in a neighbourhood belong to each issue type?
# Count issue types per neighbourhood
issue_by_quartier = (
    reports_quartier
    .groupby(["qname", "service_name"])
    .size()
    .reset_index(name="report_count")
)

# Calculate absolute number of total reports per neighbourhood
quartier_totals = (
    reports_quartier
    .groupby("qname")
    .size()
    .reset_index(name="total_reports")
)

# Join totals back
issue_by_quartier = issue_by_quartier.merge(
    quartier_totals,
    on="qname",
    how="left"
)

# Calculate share of each issue category for each neighbourhood
issue_by_quartier["share_of_reports"] = (
    issue_by_quartier["report_count"]
    / issue_by_quartier["total_reports"]
) * 100

issue_pivot = issue_by_quartier.pivot(
    index="qname",
    columns="service_name",
    values="share_of_reports"
).fillna(0)

display(issue_pivot)

service_name,Abfall/Sammelstelle,Allgemein,Beleuchtung/Uhren,Brunnen/Hydranten,Graffiti,Grünflächen/Spielplätze,Schädlinge,Signalisation/Lichtsignal,Strasse/Trottoir/Platz,VBZ/ÖV
qname,,,,,,,,,,
Affoltern,32.197757,4.528459,10.178646,1.246365,5.525550,12.796012,1.661820,15.330287,13.585376,2.949730
Albisrieden,31.516937,5.252823,6.676485,3.240059,2.601865,12.911144,2.209131,16.789396,16.445754,2.356406
Alt-Wiedikon,51.062124,5.891784,6.733467,1.122244,1.362725,5.851703,1.082164,13.226453,11.823647,1.843687
Altstetten,34.167280,6.181015,5.862154,3.213147,4.341428,8.118715,1.937699,19.009075,14.471425,2.698062
City,25.071880,7.993099,6.267970,1.782634,5.520414,5.462910,0.230017,21.506613,21.909143,4.255319
Enge,25.155166,9.784593,7.265425,1.496897,8.470245,9.200438,0.693684,19.897773,14.968967,3.066813
Escher Wyss,23.042362,3.337612,6.161746,1.155327,5.648267,9.050064,0.513479,21.822850,25.224647,4.043646
Fluntern,31.254996,5.755396,9.512390,3.597122,5.355715,12.789768,1.678657,14.228617,13.669065,2.158273
Friesenberg,23.650568,5.326705,8.948864,2.130682,4.048295,28.551136,2.627841,14.062500,9.801136,0.852273
Gewerbeschule,37.123596,7.595506,5.752809,1.573034,4.808989,8.853933,0.719101,16.089888,16.404494,1.078652
Hard,57.002111,3.659395,4.222379,1.407460,3.237157,5.137227,0.562984,11.435609,10.520760,2.814919
Hirslanden,34.522942,5.972323,14.056810,1.529497,2.986162,11.289148,1.092498,14.712309,10.924982,2.913328
Hirzenbach,35.948478,5.503513,10.304450,0.936768,1.756440,10.889930,2.107728,14.402810,13.934426,4.215457
Hochschulen,16.537102,5.017668,8.763251,3.038869,10.530035,6.077739,0.353357,21.766784,21.978799,5.936396
Hottingen,26.838046,4.987147,13.676093,2.210797,6.940874,11.053985,1.079692,16.760925,11.413882,5.038560
Höngg,29.215305,4.701686,10.408560,1.848249,3.404669,16.309987,2.853437,14.072633,14.721141,2.464332
Langstrasse,62.396761,3.481781,4.323887,0.696356,4.453441,3.562753,0.323887,9.506073,9.797571,1.457490
Leimbach,41.494436,4.451510,5.882353,3.338633,3.815580,19.554849,1.271860,8.267091,10.333863,1.589825
Lindenhof,22.419929,5.249110,5.427046,2.580071,12.900356,13.523132,0.444840,17.348754,18.060498,2.046263
Mühlebach,42.872928,5.745856,10.386740,1.215470,4.640884,5.966851,0.441989,14.917127,12.375691,1.436464
Oberstrass,24.570674,5.217966,9.313078,2.774108,8.190225,15.653897,1.387054,14.002642,14.134742,4.755614
Oerlikon,28.057796,6.250000,8.400538,2.452957,3.729839,9.912634,1.579301,19.455645,16.801075,3.360215
Rathaus,33.012380,6.533700,4.539202,1.444292,19.601100,5.914718,0.412655,8.596974,18.225585,1.719395
Saatlen,31.360947,9.763314,8.431953,1.627219,3.402367,14.497041,1.183432,17.159763,10.650888,1.923077
Schwamendingen-Mitte,32.491857,7.003257,7.573290,1.710098,1.140065,11.482085,0.651466,17.019544,16.368078,4.560261
Seebach,40.962935,4.317921,8.291937,1.337409,6.801681,10.584639,0.917081,13.412304,10.546427,2.827665
Seefeld,39.640344,4.925723,5.629398,1.172791,3.283815,18.530102,0.703675,13.291634,10.946052,1.876466
Sihlfeld,60.122699,3.911043,4.697086,1.207822,3.029141,6.825153,0.651840,10.352761,8.052147,1.150307
Unterstrass,31.095013,5.015325,9.584843,1.365283,5.990527,9.445528,1.003065,17.832265,14.990248,3.677905
Weinegg,31.311881,6.064356,11.386139,3.465347,2.970297,9.900990,1.485149,18.564356,9.405941,5.445545
Werd,60.578187,2.365309,5.190539,1.116951,2.562418,2.628121,0.459921,10.249671,12.220762,2.628121
Wipkingen,27.361069,6.771940,6.984513,1.822047,8.320680,11.812937,1.973884,18.827817,14.758579,1.366535
Witikon,23.008850,4.424779,14.336283,1.592920,3.716814,20.265487,2.300885,14.867257,13.008850,2.477876
Wollishofen,30.491687,8.171206,7.392996,2.016272,5.588964,13.052706,3.360453,14.538380,13.583304,1.804033

In [ ]:
# (5) At which neighbourhoods do people care about road markings and traffic signs (use LLM to assess which wordings are searched in descriptions and titles)?